REDIS: Adding detection of not running instances
tribe29/checkmk pull request #348
Opened 2021-03-22 14:59 UTC by m3rlinux

2021-03-23 08:20 UTC, jherbel commented
Hi,
thanks for this PR, it has been queued for internal review. Please note that this will take a while.
Best, Jörg
Internal reference: CMK-7506

2021-04-14 15:19 UTC, m3rlinux commented
Hi Jörg,
are there any news about this commit?
Thanks!

2021-04-15 06:24 UTC, jherbel requested changes
I took a closer look. Besides the one line-specific comment, I have some general remarks:

- We unfortunately cannot merge this in its current state. Any instance which is not running will now be detected and have CRIT as its monitoring status. I do not believe that this is generally desirable.
- It would be OK to make the detection of not-running instances optional. Furthermore, one would also have to make the monitoring status of not-running instances configurable. These two points (especially the first one) require modifications which should only be made after this check plugin has been ported to the new API. 
- Finally, we would definitely need to test that the parse and the check function can actually deal with the additional agent output. Again, this should only be done after porting the check (and the already existing tests) to the new API.

So, to conclude, if you really want to go along with this, you would have to first port this check plugin to the new API, including the existing tests and the parse function (in a separate PR). Then, you could go along with the actual modifications (new discovery ruleset, extending the check ruleset etc.).

2021-04-15 06:24 UTC, jherbel commented on agents/plugins/mk_redis
> -    echo "[[[$INSTANCE|${!HOST}|${!PORT}]]]"
I think this line has to stay

2021-09-30 12:11 UTC, gurubert commented
This fix with "pidof redis-server" does not work on hosts with multiple redis instances where a few are running and one or two not.

2021-10-01 07:15 UTC, jherbel commented
Closed due to inactivity

2021-10-01 07:15 UTC, closed without merging