diskspace: Fix RuntimeError in cleanup_aged
tribe29/checkmk pull request #360
Opened 2021-04-08 08:41 UTC by jplitza

The error was:
```
RuntimeError: dictionary changed size during iteration
```
To trigger it, you have to set `max_file_age` to something greater 0 in `$OMD_ROOT/etc/diskspace.conf`

We now simply iterate over a copy of the dictionary.

(Also, added a license header to make pre-commit happy)

2021-04-08 10:05 UTC, svenpanne commented on omd/packages/maintenance/diskspace
> +        for path, (_size, mtime) in dict(plugin.get('file_infos', {})).items():
The more canonical way of handling such a thing is to construct a list of items:
```python
    for path, (_size, mtime) in list(plugin.get('file_infos', {}).items()):
```

We have similar code all over the place...

2021-04-08 10:50 UTC, jplitza commented
BTW, I'm not sure about the license header, since this file seems to come from OMD originally (?), and I sure didn't check whether there once was another license on it. But since the whole repository has a GPL-2 license, I guess it already applied to the this file.

2021-04-08 17:27 UTC, jherbel requested changes

2021-04-08 17:27 UTC, jherbel commented on omd/packages/maintenance/diskspace
> +# -*- coding: utf-8 -*-
Please remove this, since it is not related to this PR

2021-04-12 06:41 UTC, jherbel approved these changes

2021-04-13 15:52 UTC, closed without merging