Special agent for fuse plugin
tribe29/checkmk pull request #383
Opened 2021-07-08 09:03 UTC by ricardomacedo

Added:

- wato plugin
- parser and tests
- special agent and tests

2021-07-26 13:09 UTC, lisa-pi commented on checks/agent_fuse_parser
> +def agent_fuse_arguments(params: dict, hostname: str, ipaddress) -> list:
It's OK not to type this.. We will rework the argument parser at some point.

2021-07-26 13:09 UTC, lisa-pi commented on cmk/gui/plugins/wato/datasource_programs.py
> +            ("password", Password(title=_("Password"), allow_empty=False)),
IndividualOrStoredPassword

2021-07-26 13:12 UTC, lisa-pi commented on cmk/special_agents/agent_fuse.py
> +    if args is None:
Add line below: 
cmk.utils.password_store.replace_passwords()

2021-07-26 13:15 UTC, lisa-pi commented on cmk/special_agents/agent_fuse.py
> +
Move state to helper function, helps keep main() as small as possible

2021-07-26 13:16 UTC, lisa-pi commented on cmk/special_agents/agent_fuse.py
> +    if state == "up":
if state != "up":
    return

2021-07-26 13:17 UTC, lisa-pi commented on cmk/special_agents/agent_fuse.py
> +    if "admin" in layout:
if "admin" not in layout:
return

2021-07-26 13:18 UTC, lisa-pi commented on cmk/special_agents/agent_fuse.py
> +    if "environments" in layout:
if "environments" not in layout:
return ..

2021-07-26 13:18 UTC, lisa-pi commented on cmk/special_agents/agent_fuse.py
> +    if "systems" in layout:
if "systems" not in layout:
return ..

2021-07-26 13:58 UTC, lisa-pi requested changes
Hi Ricardo, 

Thanks for splitting the commits up into smaller commits. It helps us with the reviews. 
Your special agent is well-written. In addition to my in-line comments, I have a couple of points

- Please name your special agent "fuse_management_central" (I have this from the title of the rulespec). More accurate names help keep the agent names unique and help us understand what they're about. 
- The naming convention for the argument parser is agent_\<agent name\>
- You don't need to type everything. What we'd like typed are the function signatures (the parameters that you feed in to your functions and their return value). Typing within the function code is only necessary when you define variables for which mypy can't derive a type. 
- For complex data structures (e.g. Dict[Tuple[str, str],....]) please try to define more accurate types. For this, most of the time classes or NamedTuples can be useful.
- What is the benefit of defining the SummaryStructure? Why not leave the objects "system_alerts", "env_alerts" and "fuse_alerts" as separate objects with their own properties? 
- In your tests, could you please use more accurate names for your input parameters? They are currently always "params" and "result". More meaningful names would help me understand better what you're testing.

You are currently missing the following:
- A stub in the directory agents/special/
- An entry in the file tests/unit/agents/special/test_special_agent_args.py, analogous to the other agents

If you have any questions, please feel free to get in touch. Happy to do a video call if that helps. 

Cheers,
Lisa

2021-08-03 14:42 UTC, ricardomacedo commented
Hi Lisa,

I just commited the changes.

Cheers,
Ricardo

2021-09-01 09:57 UTC, ricardomacedo commented
Hi @lisa-pi,

Can you give us some help to help to fix the failing check?

Cheers

2021-09-01 10:57 UTC, svenpanne commented on tests/unit/checks/test_agent_fuse_management_central.py
> +from testlib import SpecialAgent
Importing from `tests.testlib` should work.

2021-09-06 17:50 UTC, ricardomacedo commented
Hi @lisa-pi and @svenpanne,

One check failed, can you help us find out the problem?

Cheers,
Ricardo Macedo

2021-09-07 06:50 UTC, lisa-pi commented
> Hi @lisa-pi and @svenpanne,
> 
> One check failed, can you help us find out the problem?
> 
> Cheers,
> Ricardo Macedo

Hi @ricardomacedo, you must add a test case for your special agent to the test file
`unit/agents/special/test_special_agent_args.py`

2021-09-07 08:55 UTC, ricardomacedo commented
> > Hi @lisa-pi and @svenpanne,
> > One check failed, can you help us find out the problem?
> > Cheers,
> > Ricardo Macedo
> 
> Hi @ricardomacedo, you must add a test case for your special agent to the test file
> `unit/agents/special/test_special_agent_args.py`

Hi @lisa-pi,

We have the following files:

- `checks/agent_fuse_management_central` with the tests in `tests/unit/checks/test_agent_fuse_management_central.py`
- `cmk/special_agents/agent_fuse_management_central.py` with the tests in `tests/unit/cmk/special_agents/test_agent_fuse_management_central.py`
- `agents/special/agent_fuse_management_central` is just a stub

And then we also changed the file `cmk/gui/plugins/wato/datasource_programs.py`.

In the file `tests/unit/checks/test_agent_fuse_management_central.py` we have the test case for the special agent, is there something wrong or missing?

2021-09-07 09:00 UTC, lisa-pi commented
> unit/agents/special/test_special_agent_args.py

Hi @ricardomacedo, the file `unit/agents/special/test_special_agent_args.py` is an existing test file. You also need to add a test case there for your special agent. Have a look at the file, there are many examples.

2021-09-08 13:13 UTC, ricardomacedo commented
Hi @lisa-pi,

Can you help us fixing the test case for the special agent in the test file `unit/agents/special/test_special_agent_args.py`?

Cheers

2021-09-08 13:20 UTC, lisa-pi commented
> Hi @lisa-pi,
> 
> Can you help us fixing the test case for the special agent in the test file `unit/agents/special/test_special_agent_args.py`?
> 
> Cheers

Hi @ricardomacedo, your special agent should have an additional argument: "--debug". See "Details": 
```
         msg = "Special agents should support the argument '--debug'"
        # This also ensures that the parse_arguments function indeed expects
        # sys.argv[1:], i.e. the first element omitted.
>       assert parse_arguments(['--debug'] + required_args).debug is True, msg
```

2021-09-08 13:53 UTC, ricardomacedo commented
> > Hi @lisa-pi,
> > Can you help us fixing the test case for the special agent in the test file `unit/agents/special/test_special_agent_args.py`?
> > Cheers
> 
> Hi @ricardomacedo, your special agent should have an additional argument: "--debug". See "Details":
> 
> ```
>          msg = "Special agents should support the argument '--debug'"
>         # This also ensures that the parse_arguments function indeed expects
>         # sys.argv[1:], i.e. the first element omitted.
> >       assert parse_arguments(['--debug'] + required_args).debug is True, msg
> ```

Hi @lisa-pi, can you point us one example of a special agent accepting the argument --debug?

2021-09-08 14:01 UTC, lisa-pi commented
> > > Hi @lisa-pi,
> > > Can you help us fixing the test case for the special agent in the test file `unit/agents/special/test_special_agent_args.py`?
> > > Cheers
> > 
> > 
> > Hi @ricardomacedo, your special agent should have an additional argument: "--debug". See "Details":
> > ```
> >          msg = "Special agents should support the argument '--debug'"
> >         # This also ensures that the parse_arguments function indeed expects
> >         # sys.argv[1:], i.e. the first element omitted.
> > >       assert parse_arguments(['--debug'] + required_args).debug is True, msg
> > ```
> 
> Hi @lisa-pi, can you point us one example of a special agent accepting the argument --debug?

Hi @ricardomacedo , any special agent should have it. E.g. `cmk/special_agents/agent_siemens_plc.py`

2021-09-14 12:16 UTC, lisa-pi commented
Hi @ricardomacedo , it appears that something got mixed up in your last commit. Please delete it and rebase your branch on our master branch instead (make sure to do a pull from master before you rebase).
Note: we are now using black as our formatting tool. This is why you are experiencing merge conflicts. Please use black to format your code going forward. 
Sorry for the inconvenience!

2021-09-15 10:06 UTC, ricardomacedo commented
Hi @lisa-pi,

Branch rebased, files formated and all checks are passing.

Cheers

2021-09-15 16:34 UTC, lisa-pi requested changes
Hi @ricardomacedo , 
Thanks for your PR. Here's a few comments. If you've any questions, let me know. 
Cheers, 
Lisa

2021-09-15 16:34 UTC, lisa-pi commented on cmk/special_agents/agent_fuse_management_central.py
> +def get_state(layout_response_code: int, summary_response_code: int, data) -> str:
I think you want to make this a service later. In that case, it is better to give out the raw information here and let the check decide what to do with it later. It means more flexibility and also that the evaluation is always in the same place.

2021-09-15 16:34 UTC, lisa-pi commented on cmk/special_agents/agent_fuse_management_central.py
> +    sys.stdout.write("<<<fuse_instance:sep(0)>>>\n")
`fuse_management_central_instance`

2021-09-15 16:34 UTC, lisa-pi commented on cmk/special_agents/agent_fuse_management_central.py
> +    sys.stdout.write("<<<fuse_system_alerts:sep(0)>>>\n")
`fuse_management_central_system_alerts`

2021-09-15 16:34 UTC, lisa-pi commented on cmk/special_agents/agent_fuse_management_central.py
> +    sys.stdout.write("<<<fuse_env_alerts:sep(0)>>>\n")
`fuse_management_central_env_alerts`

2021-09-15 16:34 UTC, lisa-pi commented on cmk/special_agents/agent_fuse_management_central.py
> +    sys.stdout.write("<<<fuse_admin_alerts:sep(0)>>>\n")
`fuse_management_central_admin_alerts`

2021-09-15 16:34 UTC, lisa-pi commented on cmk/special_agents/agent_fuse_management_central.py
> +class FuseRequest:
I think we don't need this class. See below.

2021-09-15 16:34 UTC, lisa-pi commented on cmk/special_agents/agent_fuse_management_central.py
> +    layout_response: LayoutResponse = layout_request.get_layout()
`layout_response = requests.get(f'{opt.url}/layout', auth=(opt.user, opt.password))`

For error handling: when a special agent returns a non-zero exit code, the first line of the error message written to stderr is shown by the "Check_MK" service and it returns a state CRIT. You can use this fact for your error handling here. Eg.

```
try: 
    layout_response = requests.get(f'{opt.url}/layout', auth=(opt.user, opt.password))
except requests.exceptions.RequestException:
    print('Some useful error text', file=sys.stderr)
    raise SystemExit(1)
```

2021-09-15 16:34 UTC, lisa-pi commented on cmk/special_agents/agent_fuse_management_central.py
> +    summary_response: SummaryResponse = summary_request.get_summary()
See above

2021-11-18 08:52 UTC, jherbel commented
Closed this due to inactivity

2021-11-18 08:52 UTC, closed without merging