Added new hardware models
tribe29/checkmk pull request #460
Opened 2022-05-02 07:40 UTC by pechsteinma

## General information

Added new hardware models 9200 and 9200L
Added comments to snmp_scan_function for better understanding which models are supported.

Manufacturer: Cisco
Model: C9200 amd C9200L
Software: IOS-XE

## Example of a 9200L switch stack

OMD[xxx]:~/local/share/check_mk/checks$ snmpwalk -v 2c -c xxx 10.x.x.x 1.3.6.1.2.1.1.2.0
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.9.1.2694

2022-07-01 16:43 UTC, mo-ki requested changes
Hi Martin,
We're trying not to extend any plugins without migrating them, so I did just that for this plugin. Would you mind to rebase this? The required changes should be self-explanatory.
Cheers,
Moritz

2022-07-04 04:40 UTC, pechsteinma commented
> We're trying not to extend any plugins without migrating them, so I did just that for this plugin.

Sorry, but I didn't get it. So you migrated the check? To where? 

> The required changes should be self-explanatory.

For me: no. Do you mean that I need to update my CheckMK installation to the latest version to get the updated check?

2022-07-04 06:32 UTC, mo-ki commented
Sorry, I was not being clear.
I migrated the check plugin to the new API, it is now located in `cmk/base/plugins/agent_based/cisco_stack.py` ([here](https://github.com/tribe29/checkmk/blob/master/cmk/base/plugins/agent_based/cisco_stack.py)).
You'll have to add those OIDs in the `detect` specification (around line 73) -- how you can extend the lines there is the bit that I assume you will figure out by looking at them.
After we have merged the changes, they will be released with the next Checkmk version (so probably 2.2), but that would have been the case anyway.

2022-07-04 07:03 UTC, pechsteinma commented
Topic will be continued in #484

2022-07-04 07:03 UTC, closed without merging