agent_prometheus: fixed promql mode (init, query quoting), API prefix…
tribe29/checkmk pull request #513
Opened 2022-09-09 09:22 UTC by simonmeggle

- Handling of Prometheus API prefix was broken. (`https://customprefix192.33.22.11:443/api/v1` - should be `https://192.33.22.11:443/customprefix/api/v1` ) Related forum post: https://forum.checkmk.com/t/prometheus-with-custom-url/28679/2
- The special agent runs into a timeout if you only specify a custom PromQL query (=without setting any other scrape target). It directly tries to scrape connected targets even if they are not needed. This fails for PromQL-only rules. I made this a property so that the associated method gets only called when needed. 
- The Prometheus API is not happy with quoted query strings (e.g. `query?query=notifications_sent_out_total%7Binstance%3Dweb-push%3A8080%2C%20job%3Dweb-push%2C%20notification_type%3DPushNotification%`). Without quoting, it runs fine. 

Best regards,
Simon

2022-09-09 09:37 UTC, simonmeggle commented
(Honestly, I have no clue what the formatting test is telling me... )

2022-09-09 21:53 UTC, mo-ki commented
> (Honestly, I have no clue what the formatting test is telling me... )

[_Black_](https://github.com/psf/black#readme) is telling you to use double quotes in `'path-prefix'` (it should read `"path-prefix"`) and to replace
```
    connection_args.update({...})
```
by
```
  connection_args.update(
      {...}
  )
```
(because it deems the line too long)

2022-09-16 10:31 UTC, SoloJacobs commented
Hi Simon,

I briefly looked at your commit today. It appears to me, that you have to fix both pylint and the unit-tests. Both fixes should straight-forward. You can see CONTRIBUTING.md for details on what we require.
```
pylint: cmk/special_agents/agent_prometheus.py:30:0: W0611: Unused quote imported from urllib.parse (unused-import)
unit-test: tests/unit/cmk/special_agents/utils/test_prometheus.py:148: AssertionError
```
I will try to replicate you issue anyway, and then confirm that the commit fixes it. This may take until next week, though. Could you explain why you removed quote?

Kind regards, Sol

2022-09-16 11:33 UTC, simonmeggle commented
Thanks, Sol!

> Could you explain why you removed quote?

The PromQL as copied from the Prometheus UI did simply not work at all. 
I have read in the [Prometheus documentation](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries) that URL encoding can be used only with POST requests. As we are doing GET, I tried without encoding and it worked.

2022-09-19 14:52 UTC, SoloJacobs commented on cmk/special_agents/utils/prometheus.py
> +        path_prefix = path_prefix + "/"
Ok to ignore: This is reimplementing existing functionality inside of parse_api_url. I would change it.

2022-09-19 15:03 UTC, SoloJacobs requested changes
Ok, so as is, this would break existing setups. Namely, those setups, where the path prefix is used for what it is (a url prefix). I think the correct solution would be to 

- Introduce a new value in the prometheus rule (called `url_prefix`).
- Write a transform for the valuespec inside `cmk/gui/plugins/wato/special_agents/prometheus.py`. Then, migrate existing `path_prefix` values to `url_prefix`.

For the `quote` change: If I understand your change correctly, the main difference is whether web-push%3A8080 is matched to the label web-push:8080. So, Prometheus will not return an error, but simply that there are no such metrics?

2022-09-21 07:53 UTC, SoloJacobs commented
**Prefix** 
Let's first answer your questions as best as I can.

> I just wonder if it makes any sense to provide a prefix prometheus in front of the host IP?

URL prefixes are used by at least some of our customers. We only implement features on demand. Whether any of those customers are using Prometheus I do not know. URL prefixes only make sense for host names (which would be affected by your change).

> Did anybody get this working?

Yes, I talked with some of our customers just last week. I also have a running setup at this very moment.

> I am just curious, what would break?

I honestly don't know. However, I am unwilling to break somebodies setup just because I was unable to imagine their use case.

_Proposal._ I realised that we only need the `Transform` in the 2.1.0 and thus, it is not necessary for your pull request. I will probably implement the fix myself for the 2.1.0. then. You still need to fix the unit tests or allow me to edit your commit on your behalf.

**Quote**
The Prometheus agent uses the `request` library under the hood. This means, even if you remove the `quote`, some quoting will take place nonetheless. Here is an example:
```
currently sent by Checkmk: query?query=notifications_sent_out_total%7Binstance%3Dweb-push%3A8080%2C%20job%3Dweb-push%2C%20notification_type%3DPushNotification%7D
sent by Checkmk, if I merge your pull request: query?query=notifications_sent_out_total%7Binstance%3Dweb-push:8080%2C%20job%3Dweb-push%2C%20notification_type%3DPushNotification%7D
```
I have checked whether Prometheus will return the value with and without quoting. For me, both setups work just fine. I used the following metric to test this:
`prometheus_notifications_latency_seconds{alertmanager="http://172.17.0.3:9093/api/v2/alerts",quantile="0.5"}`

_Proposal._ Remove your change to `quote`. Without information on how to replicate your issue, this change only makes it more likely for your change to be reverted.

2022-10-07 11:33 UTC, closed without merging