Update check_mk_agent.openbsd
tribe29/checkmk pull request #538
Opened 2022-11-04 17:17 UTC by cmarbach

Detect 10 Gbps interface

Thank you for your interest in contributing to Checkmk!
Unfortunately, due to our current work load, we only consider pure bug fixes as stated in our [Readme](https://github.com/tribe29/checkmk#want-to-contribute).
This means any new pull request that is not a pure bug fix will be closed.
Instead of creating a PR, please consider sharing new check plugins, agent plugins, special agents or notification plugins via the [Checkmk Exchange](https://exchange.checkmk.com/).

## General information

Please give a brief summary of the affected device, software or appliance.
Keep in mind that we are experts in monitoring, but we cannot be experts on all supported devices.
A little context will help us assess your proposed change.

## Bug reports

Please include:

+ Your operating system name and version
openbsd 6.9
+ Any details about your local setup that might be helpful in troubleshooting
checkmk server 2.1.0p12
+ Detailed steps to reproduce the bug
connect a 10 Gbps network interface, this will report "10GMb/s" which is not valid
+ An agent output or SNMP walk
[vmx0]
        Speed: 10GMb/s
        Duplex: Half
        Auto-negotiation: on
        Link detected: yes
        Address: 00:50:56:b5:57:9a
+ The ID of a submitted crash report for reference (if applicable)
N/A

## Proposed changes

Sometimes it is hard for us to assess the quality of a fix.
While it may work for you, it is our job to ensure that it works for everybody.
These are some ways to help us:

+ What is the expected behavior?
10000Mb/s
+ What is the observed behavior?
10GMb/s
+ If it's not obvious from the above: In what way does your patch change the current behavior?
If a "G" is present in the $SP variable, then it changes the value of $SP to 10000.
This may be improved to take into consideration 20/25/100 Gb/s interfaces
+ Consider writing a unit test that would have failed without your fix.
+ Is this a new problem? What made you submit this PR (new firmware, new device, changed device behavior)?

2022-11-15 11:10 UTC, kain88-de requested changes
Thanks for your contribution. I cannot merge this at the moment as this does not work on NICs that support higher speeds than 10G. Can you make the changes to make the conversion based on the value. Something like this should work

```bash
case "$SP" in
  *G*) SP=$(echo $SP   | awk '{ split($0,a,"G"); print a[1] * 1000 }')
esac
```

2022-11-15 11:10 UTC, kain88-de commented on agents/check_mk_agent.openbsd
> +                        SP=10000
This line is unnecessary.

2022-11-15 11:10 UTC, kain88-de commented on agents/check_mk_agent.openbsd
> +                        *G*) SP=10000
This would break on 20G or 40G NICs. We should try to convert the value correctly instead of just guessing this is a 10G NIC.

2023-03-25 18:56 UTC, cmarbach commented
Thanks a lot, this works.

2023-03-25 18:56 UTC, closed without merging