check_sql: allow configuration of metric name
tribe29/checkmk pull request #74
Opened 2019-11-08 15:08 UTC by gurubert

This patch adds an optional argument to --metrics that will be used as metric name for the perfomance data.
If no argument is passed, "performance_data" is still the default metric name.

2019-11-12 08:58 UTC, jonaskluger commented
Hello Robert,

thank you for this request. We will have a closer look at your patch and discuss internally on how and if we can implement it into the official code base.

Internal Ref: CMK-3202

2021-04-15 05:47 UTC, auchri commented
Hi @jherbel, it would be awesome if you could merge this!

2021-12-29 18:38 UTC, mo-ki requested changes
Hi Robert!
If you can address the mentioned issues, I think we should mere this. Looks like a straightforward improvement to me.

2021-12-29 18:38 UTC, mo-ki commented on cmk/gui/plugins/wato/active_checks.py
> +    return perfdata
If you swap those around, you can loose the 'not'

2021-12-29 18:38 UTC, mo-ki commented on cmk/gui/plugins/wato/active_checks.py
> +                 TextAscii(
TextInput  (Ascii vs. Unicode is legacy)

2021-12-29 18:38 UTC, mo-ki commented on cmk/gui/plugins/wato/active_checks.py
> +                 ),
I think we should also have `allow_empty=False`.

2021-12-29 18:38 UTC, mo-ki commented on checks/check_sql
> +        args.append("--metrics=%s" % params["perfdata"])
There are some issues here.
I don't think we can have the `not params["perfdata"]` case, if we prohibit empty strings (see below).
Changing the functions argument (params) is dangerous. I suggest
```
if (metrics:=params.get("perfdata")) is not None:
    args.append(f"--metrics={metrics}")
```

Please add a test for this in tests/unit/checks/test_check_sql.py!

2022-03-30 06:35 UTC, mo-ki commented
Believe it or not, I am about to merge this.

2022-03-30 06:40 UTC, gurubert commented
😱😊

2022-03-30 07:52 UTC, closed without merging